# Generated by Django 5.0.2 on 2024-02-20 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Letters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=50, verbose_name='ФИО отправителя')),
                ('recipent_name', models.CharField(max_length=50, verbose_name='ФИО получателя')),
                ('departure_name', models.CharField(max_length=250, verbose_name='пункт отправки')),
                ('arrival_name', models.CharField(max_length=250, verbose_name='пункт получения')),
                ('departure_index', models.IntegerField(verbose_name='индекс места отправки')),
                ('arrival_index', models.IntegerField(verbose_name='индекс места получения')),
                ('letter_type', models.IntegerField(verbose_name='тип письма')),
                ('letter_weight', models.IntegerField(verbose_name='вес письма')),
            ],
            options={
                'verbose_name': 'Письмо',
                'verbose_name_plural': 'Письма',
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=50, verbose_name='ФИО отправителя')),
                ('recipent_name', models.CharField(max_length=50, verbose_name='ФИО получателя')),
                ('departure_name', models.CharField(max_length=250, verbose_name='пункт отправки')),
                ('arrival_name', models.CharField(max_length=250, verbose_name='пункт получения')),
                ('departure_index', models.IntegerField(verbose_name='индекс места отправки')),
                ('arrival_index', models.IntegerField(verbose_name='индекс места получения')),
                ('phone', models.CharField(max_length=20, verbose_name='телефон для извещения')),
                ('package_type', models.IntegerField(verbose_name='тип посылки')),
                ('amount', models.IntegerField(verbose_name='сумма платежа')),
            ],
            options={
                'verbose_name': 'Посылка',
                'verbose_name_plural': 'Посылки',
            },
        ),
    ]
